scriptencoding utf-8

source ~/.vim/vim-plug.vim

set runtimepath+=$GOROOT/misc/vim
syntax on
filetype plugin indent on
colorscheme railscasts

runtime options.vim
runtime plugin_options.vim
runtime mappings.vim
