# set the prefix I'm used to (space)
unbind C-b
set -g prefix C-Space

setw -g mode-keys vi # use vi keys in copy mode
setw -g automatic-rename on
# setw -g aggressive-resize on # something about the minimum size when multiple terminals are viewing a single pane

set -g base-index 1 # 1-index window numbers
set -g bell-action none
set -g display-time 4000 # show messages on the status line for 4s
set -g escape-time 10 # ms to wait after an escape to figure it out
set -g focus-events on # whether to send focus events when switching pane focus 
set -g history-limit 10000
set -g renumber-windows on
set -g status-keys emacs # keys to use when actually inputting commands on the status line
set -g status-right '%d-%b-%y '

# color options that may or may not be good
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g xterm-keys on

# status bar colors
setw -g window-status-current-style fg='#5C995D',bg=black
setw -g message-style fg=black,bg='#5C995D'
set -g status-style fg=black,bg='#5C995D'

bind C-Space last-window
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H swap-window -dt -1
bind L swap-window -dt +1

bind c new-window -a -c "$HOME"

set -g mouse on
# bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
# bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down
# bind-key -T root WheelUpPane select-pane -t =\; copy-mode -e\; send-keys -M

set-option -g set-clipboard on

# don't scroll back to the bottom when copying with mouse
# bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy
# bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear pbcopy

# bring up a fzf pane with any URLs found in the pane, and open selected ones in the default browser
bind-key C-u run-shell -b "tmux capture-pane -J -p | grep -oE '(https?):\/\/.*[^>]' | fzf-tmux -d20 --multi --bind alt-a:select-all,alt-d:deselect-all | xargs open"

source-file -q ~/.tmux.local.conf

set -g @plugin 'tmux-plugins/tmux-yank'
run -b '~/.tmux/plugins/tpm/tpm'
